{{- if or (.Values.windowsEnforcer.allWinNodes.enable) (.Values.windowsEnforcer.WinLinuxNodes.enable) }}
{{- if not .Values.windowsEnforcer.enforcerTokenSecretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-windows-enforcer-token
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-windows-ds
    aqua.component: windows-enforcer
{{ include "aqua.labels" . | indent 4 }}
type: Opaque
data:
  windows-token: {{ (required "A valid .Values.windowsEnforcer.enforcerToken entry required!" .Values.windowsEnforcer.enforcerToken) | b64enc }}
{{- end }}
{{- end }}
